[package]
name = "todos"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
colored = "2.1.0"
rusqlite = "0.32.0"

[[bin]]
name = "todos"
path = "src/main.rs"